openapi: 3.0.1
info:
  title: WorkBoard External Public Activity (Action Items) Activity (Action Items) Activity (Action Items) API
  description: <h4>This is the API documentation for WorkBoard's version 1 REST API.</h4><p>WorkBoard's API provides resources to allow developers to interact with user, goal, and metric data in WorkBoard. All resources can be accessed via REST with GET, POST, PUT, PATCH and DELETE requests. For GET requests, query parameters can be passed as part of the request URL. All GET, POST, PUT, PATCH and DELETE requests must include the Bearer Token authorization header with the provided token you generate.</p><p>Click here to view the [changelog](./changes.html).<p>Click here to view the [Open API JSON file](./openapi.json).</p><p><strong>If you are interested in working in a demo instance, please contact your WorkBoard representative.<br/>WorkBoard's production server API root is https://www.myworkboard.com/wb/apis.</strong></p>
  version: 1.0.0
servers:
- url: https://demo.biz.wobo-int.com/wb/apis
  description: Demo Server
tags:
- name: Activity (Action Items)
paths:
  /activity:
    get:
      summary: List the details of existing action items. By default, this query will return the first 50 items that match your request parameters. Use the offset and limit parameters to return a different set.
      description: List the details of existing action items. By default, this query will return the first 50 items that match your request parameters. Use the offset and limit parameters to return a different set.
      tags:
      - Activity (Action Items)
      parameters:
      - name: ai_id
        description: The unique numerical id assigned to each action item in WorkBoard.
        in: query
        required: false
        schema:
          type: integer
      - name: ai_owner
        description: The numerical user id or email address of the user who currently owns the action item.
        in: query
        schema:
          type: string
      - name: next_page_token
        description: If you have made a pagination request, you will receive a next_page_token value which can be passed as a parameter in your next request.
        in: query
        schema:
          type: string
      - name: due_date_range
        description: 'Return action items with due dates in the specified range. Dates must be formatted as UTC timestamps and comma-separated: startdate,enddate'
        in: query
        schema:
          type: string
      - name: priority
        description: 'Return action items with the specified priority ratings. Permitted values are: "1" (highest), "2" (high), "3" (normal)'
        in: query
        schema:
          type: string
      - name: state
        description: 'Return action items with the specified state. Permitted values are: "0" (done), "1" (doing), "2" (next), "4" (pause)'
        in: query
        schema:
          type: string
      - name: ai_state
        description: 'Return action items with the specified state. Multiple values can be comma separated. Permitted values are: "0" (done), "1" (doing), "2" (next), "4" (pause)'
        in: query
        schema:
          type: string
      - name: rag
        description: 'Return action items with the specified level of effort. Permitted values are: "1" (easy), "2" (medium), "3" (huge)'
        in: query
        schema:
          type: string
      - name: effort
        description: 'The numeric value for the effort: 1 = easy, 2 = medium, 3 = huge.'
        in: query
        schema:
          type: integer
      - name: opt_filters
        description: 'Limit responses based on action item properties. Only one value may be passed in this parameter (commas are not allowed). Possible values are: due_today, due_this_week, request_for_me, work_i_delegated, In_the_loop, late, risk'
        in: query
        schema:
          type: string
      - name: ai_tags[]
        description: An array of the numerical tag identifiers for Action Items.
        in: query
        schema:
          type: array
          items:
            type: integer
      - name: limit
        description: The number of teams returned per page. Permitted values are integers greater than or equal to 0. The default value is 15.
        in: query
        schema:
          type: integer
      - name: offset
        description: Specify the starting point for the results returned. Permitted values are integers greater than or equal to 0. The default value is 0.
        in: query
        schema:
          type: integer
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    readOnly: true
                  message:
                    type: string
                    readOnly: true
                  data:
                    type: object
                    readOnly: true
                    properties:
                      totalCount:
                        type: integer
                      activity:
                        description: Returns an array of activities if `ai_id` is not passed. Returns a single activity object when `ai_id` is passed.
                        oneOf:
                        - type: object
                          properties:
                            ai_id:
                              type: string
                            ai_description:
                              type: string
                            ai_created_at:
                              type: string
                            ai_state:
                              type: string
                            ai_rating:
                              type: string
                            ai_priority:
                              type: string
                            ai_effort:
                              type: string
                            ai_files:
                              type: array
                              items:
                                type: object
                                properties:
                                  file_id:
                                    type: string
                                  file_name:
                                    type: string
                                  file_url:
                                    type: string
                                  file_owner:
                                    type: string
                            ai_sub_actions:
                              type: array
                              items:
                                type: object
                                properties:
                                  sub_ai_id:
                                    type: string
                                  sub_ai_description:
                                    type: string
                                  sub_ai_owner:
                                    type: string
                            ai_comments:
                              type: array
                              items:
                                type: object
                                properties:
                                  comment_id:
                                    type: string
                                  comment:
                                    type: string
                                  comment_owner:
                                    type: string
                                  comment_timestamp:
                                    type: string
                            ai_due_date:
                              type: string
                            ai_workstream:
                              type: string
                            ai_team:
                              type: string
                              nullable: true
                            ai_workstream_name:
                              type: string
                            ai_loop_members:
                              type: array
                              items:
                                type: object
                                properties:
                                  user_id:
                                    type: string
                                  user_email:
                                    type: string
                            ai_tags:
                              type: string
                              nullable: true
                            ai_due_before:
                              type: string
                            ai_owner:
                              type: string
                            ai_created_by:
                              type: string
                            ai_url:
                              type: string
                            ai_completed_at:
                              type: string
                              nullable: true
                        - type: array
                          items:
                            type: object
                            properties:
                              ai_id:
                                type: string
                              ai_description:
                                type: string
                              ai_created_at:
                                type: string
                              ai_state:
                                type: string
                              ai_rating:
                                type: string
                              ai_priority:
                                type: string
                              ai_effort:
                                type: string
                              ai_files:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    file_id:
                                      type: string
                                    file_name:
                                      type: string
                                    file_url:
                                      type: string
                                    file_owner:
                                      type: string
                              ai_sub_actions:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    sub_ai_id:
                                      type: string
                                    sub_ai_description:
                                      type: string
                                    sub_ai_owner:
                                      type: string
                              ai_comments:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    comment_id:
                                      type: string
                                    comment:
                                      type: string
                                    comment_owner:
                                      type: string
                                    comment_timestamp:
                                      type: string
                              ai_due_date:
                                type: string
                              ai_workstream:
                                type: string
                              ai_team:
                                type: string
                                nullable: true
                              ai_workstream_name:
                                type: string
                              ai_loop_members:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    user_id:
                                      type: string
                                    user_email:
                                      type: string
                              ai_tags:
                                type: string
                                nullable: true
                              ai_due_before:
                                type: string
                              ai_owner:
                                type: string
                              ai_created_by:
                                type: string
                              ai_url:
                                type: string
                              ai_completed_at:
                                type: string
                                nullable: true
        '400':
          description: Unauthorized / Invalid
          content:
            application/json:
              schema:
                properties:
                  success:
                    type: boolean
                    description: 'false'
                  error:
                    type: string
                  error_description:
                    type: string
                example:
                  success: false
                  error: ''
                  error_description: ''
      security:
      - bearerAuth: []
    post:
      summary: Create an action item.
      description: Create a new action item. Request parameters should be passed in the POST request or in the payload (as JSON). To create an action item with a comment, sub-action, or tag, it should be passed as raw JSON, along with the ai_id either as a request parameter or in the URL.
      tags:
      - Activity (Action Items)
      requestBody:
        content:
          application/json:
            schema:
              properties:
                ai_description:
                  type: string
                  description: The name (or description) of the action item.
                ai_note:
                  type: string
                  description: The formatted notes associated with an action item.
                ai_owner:
                  type: string
                  description: The numerical user id of the owner of the action item.
                ai_workstream:
                  type: string
                  description: The unique numerical id of the Workstream to which the action item belongs
                ai_team:
                  type: string
                  description: The unique numerical id of the team to which the action item belongs
                ai_due_date:
                  type: string
                  description: The action item's due date (in UNIX timestamp format)
                ai_state:
                  type: string
                  description: 'The current state of the action item. Possible values are: "next" "doing" "done" "pause"'
                ai_priority:
                  type: string
                  description: 'The current priority of the action item. Possible values are: "low" "med" "high"'
                ai_rating:
                  type: string
                  description: 'The current RAG rating of the action item. Possible values are: "red" "amber" "green"'
                ai_effort:
                  type: string
                  description: 'The current effort of the action item. Possible values are: "easy" "medium" "huge"'
                ai_tags:
                  type: array
                  description: Tags that have been applied to the action item. Each tag contains the following nested attributes:<br/>tag_id - the unique numerical id assigned to each tag<br/>tag_name - the name of the tag
                  items:
                    type: object
                    properties:
                      tag_id:
                        type: string
                      tag_name:
                        type: string
                ai_comments:
                  type: array
                  description: All comments that have been added to the action item. Each comment contains the following nested attributes:<br/>comment - the text of the comment<br/>comment_id - the unique numerical id assigned to each comment<br/>comment_owner - the numerical user id of the person who posted the comment
                  items:
                    type: object
                    properties:
                      comment:
                        type: string
                      comment_id:
                        type: string
                      comment_owner:
                        type: string
              required:
              - ai_description
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    readOnly: true
                  message:
                    type: string
                    readOnly: true
                  data:
                    type: object
                    readOnly: true
                    properties:
                      totalCount:
                        type: integer
                      activity:
                        type: object
                        properties:
                          ai_id:
                            type: string
                          ai_description:
                            type: string
                          ai_created_at:
                            type: string
                          ai_state:
                            type: string
                          ai_rating:
                            type: string
                          ai_priority:
                            type: string
                          ai_effort:
                            type: string
                          ai_files:
                            type: array
                            items:
                              type: object
                              properties:
                                file_id:
                                  type: string
                                file_name:
                                  type: string
                                file_url:
                                  type: string
                                file_owner:
                                  type: string
                          ai_sub_actions:
                            type: array
                            items:
                              type: object
                              properties:
                                sub_ai_id:
                                  type: string
                                sub_ai_description:
                                  type: string
                                sub_ai_owner:
                                  type: string
                          ai_comments:
                            type: array
                            items:
                              type: object
                              properties:
                                comment_id:
                                  type: string
                                comment:
                                  type: string
                                comment_owner:
                                  type: string
                                comment_timestamp:
                                  type: string
                          ai_due_date:
                            type: string
                          ai_workstream:
                            type: string
                          ai_team:
                            type: string
                            nullable: true
                          ai_workstream_name:
                            type: string
                          ai_loop_members:
                            type: array
                            items:
                              type: object
                              properties:
                                user_id:
                                  type: string
                                user_email:
                                  type: string
                          ai_tags:
                            type: string
                            nullable: true
                          ai_due_before:
                            type: string
                          ai_owner:
                            type: string
                          ai_created_by:
                            type: string
                          ai_url:
                            type: string
                          ai_completed_at:
                            type: string
                            nullable: true
                        description: Returns a single activity object.
        '400':
          description: Unauthorized / Invalid
          content:
            application/json:
              schema:
                properties:
                  success:
                    type: boolean
                    description: 'false'
                  error:
                    type: string
                  error_description:
                    type: string
                example:
                  success: false
                  error: ''
                  error_description: ''
      security:
      - bearerAuth: []
  /activity/{ai_id_path}:
    get:
      summary: List the details of existing action items. By default, this query will return the first 50 items that match your request parameters. Use the offset and limit parameters to return a different set.
      description: List the details of existing action items. By default, this query will return the first 50 items that match your request parameters. Use the offset and limit parameters to return a different set.
      tags:
      - Activity (Action Items)
      parameters:
      - name: ai_id_path
        description: The unique numerical id assigned to each action item in WorkBoard.
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    readOnly: true
                  message:
                    type: string
                    readOnly: true
                  data:
                    type: object
                    readOnly: true
                    properties:
                      totalCount:
                        type: integer
                      activity:
                        type: object
                        properties:
                          ai_id:
                            type: string
                          ai_description:
                            type: string
                          ai_created_at:
                            type: string
                          ai_state:
                            type: string
                          ai_rating:
                            type: string
                          ai_priority:
                            type: string
                          ai_effort:
                            type: string
                          ai_files:
                            type: array
                            items:
                              type: object
                              properties:
                                file_id:
                                  type: string
                                file_name:
                                  type: string
                                file_url:
                                  type: string
                                file_owner:
                                  type: string
                          ai_sub_actions:
                            type: array
                            items:
                              type: object
                              properties:
                                sub_ai_id:
                                  type: string
                                sub_ai_description:
                                  type: string
                                sub_ai_owner:
                                  type: string
                          ai_comments:
                            type: array
                            items:
                              type: object
                              properties:
                                comment_id:
                                  type: string
                                comment:
                                  type: string
                                comment_owner:
                                  type: string
                                comment_timestamp:
                                  type: string
                          ai_due_date:
                            type: string
                          ai_workstream:
                            type: string
                          ai_team:
                            type: string
                            nullable: true
                          ai_workstream_name:
                            type: string
                          ai_loop_members:
                            type: array
                            items:
                              type: object
                              properties:
                                user_id:
                                  type: string
                                user_email:
                                  type: string
                          ai_tags:
                            type: string
                            nullable: true
                          ai_due_before:
                            type: string
                          ai_owner:
                            type: string
                          ai_created_by:
                            type: string
                          ai_url:
                            type: string
                          ai_completed_at:
                            type: string
                            nullable: true
                        description: Returns an array of activities if `ai_id` is not passed. Returns a single activity object when `ai_id` is passed.
        '400':
          description: Unauthorized / Invalid
          content:
            application/json:
              schema:
                properties:
                  success:
                    type: boolean
                    description: 'false'
                  error:
                    type: string
                  error_description:
                    type: string
                example:
                  success: false
                  error: ''
                  error_description: ''
      security:
      - bearerAuth: []
    put:
      summary: Update an activity.
      description: Update an existing action item. Request parameters should be passed in the payload (as JSON). Note that the ai_id parameter is required.<br/>To update an action item with a comment, sub-action, or tag, it should be passed as raw JSON, along with the `ai_id` either as a request parameter or in the URL.
      tags:
      - Activity (Action Items)
      parameters:
      - name: ai_id_path
        description: The unique numerical id assigned to each action item in WorkBoard.
        in: path
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              properties:
                ai_description:
                  type: string
                  description: The name (or description) of the action item.
                ai_note:
                  type: string
                  description: The formatted notes associated with an action item.
                ai_owner:
                  type: string
                  description: The numerical user id of the owner of the action item.
                ai_workstream:
                  type: string
                  description: The unique numerical id of the Workstream to which the action item belongs
                ai_team:
                  type: string
                  description: The unique numerical id of the team to which the action item belongs
                ai_due_date:
                  type: string
                  description: The action item's due date (in UNIX timestamp format)
                ai_state:
                  type: string
                  description: 'The current state of the action item. Possible values are: "next" "doing" "done" "pause"'
                ai_priority:
                  type: string
                  description: 'The current priority of the action item. Possible values are: "low" "med" "high"'
                ai_rating:
                  type: string
                  description: 'The current RAG rating of the action item. Possible values are: "red" "amber" "green"'
                ai_effort:
                  type: string
                  description: 'The current effort of the action item. Possible values are: "easy" "medium" "huge"'
                ai_tags:
                  type: array
                  description: Tags that have been applied to the action item. Each tag contains the following nested attributes:<br/>tag_id - the unique numerical id assigned to each tag<br/>tag_name - the name of the tag
                  items:
                    type: object
                    properties:
                      tag_id:
                        type: string
                      tag_name:
                        type: string
                ai_comments:
                  type: array
                  description: All comments that have been added to the action item. Each comment contains the following nested attributes:<br/>comment - the text of the comment<br/>comment_id - the unique numerical id assigned to each comment<br/>comment_owner - the numerical user id of the person who posted the comment
                  items:
                    type: object
                    properties:
                      comment:
                        type: string
                      comment_id:
                        type: string
                      comment_owner:
                        type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    readOnly: true
                  message:
                    type: string
                    readOnly: true
                  data:
                    type: object
                    readOnly: true
                    properties:
                      totalCount:
                        type: integer
                      activity:
                        type: object
                        properties:
                          ai_id:
                            type: string
                          ai_description:
                            type: string
                          ai_created_at:
                            type: string
                          ai_state:
                            type: string
                          ai_rating:
                            type: string
                          ai_priority:
                            type: string
                          ai_effort:
                            type: string
                          ai_files:
                            type: array
                            items:
                              type: object
                              properties:
                                file_id:
                                  type: string
                                file_name:
                                  type: string
                                file_url:
                                  type: string
                                file_owner:
                                  type: string
                          ai_sub_actions:
                            type: array
                            items:
                              type: object
                              properties:
                                sub_ai_id:
                                  type: string
                                sub_ai_description:
                                  type: string
                                sub_ai_owner:
                                  type: string
                          ai_comments:
                            type: array
                            items:
                              type: object
                              properties:
                                comment_id:
                                  type: string
                                comment:
                                  type: string
                                comment_owner:
                                  type: string
                                comment_timestamp:
                                  type: string
                          ai_due_date:
                            type: string
                          ai_workstream:
                            type: string
                          ai_team:
                            type: string
                            nullable: true
                          ai_workstream_name:
                            type: string
                          ai_loop_members:
                            type: array
                            items:
                              type: object
                              properties:
                                user_id:
                                  type: string
                                user_email:
                                  type: string
                          ai_tags:
                            type: string
                            nullable: true
                          ai_due_before:
                            type: string
                          ai_owner:
                            type: string
                          ai_created_by:
                            type: string
                          ai_url:
                            type: string
                          ai_completed_at:
                            type: string
                            nullable: true
                        description: Returns an array of activities if `ai_id` is not passed. Returns a single activity object when `ai_id` is passed.
        '400':
          description: Unauthorized / Invalid
          content:
            application/json:
              schema:
                properties:
                  success:
                    type: boolean
                    description: 'false'
                  error:
                    type: string
                  error_description:
                    type: string
                example:
                  success: false
                  error: ''
                  error_description: ''
      security:
      - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      description: JWT Authorization header using the Bearer scheme.
      scheme: bearer
      bearerFormat: JWT
